#!/bin/bash

# Check if all required arguments are provided
if [ $# -ne 2 ]; then
    echo "Usage: $0 rule_id email"
    exit 1
fi

rule_id="$1"
email="$2"

domain=`echo $email | awk -F@ '{print $2}'`
uname=`echo $email | awk -F@ '{print $1}'`

output_dir="/etc/dovecot/sieve"
mailhomedir="/home/vmail"
maildir="${mailhomedir}/${domain}"
user_maildir="${maildir}/${uname}"

sieve_file="${user_maildir}/.dovecot.sieve"

# Find the rule file and handle the case when no file is found
rule_filename=$(find ${output_dir} -name "${uname}-rule-*-${rule_id}.sieve")
rule_filename=$(basename $rule_filename)

# Check if rule_filename is empty
if [ -z "$rule_filename" ]; then
    echo "Rule file not found"
    exit 1
fi

rule_file_without_extension=$(echo "$rule_filename" | sed 's/\.sieve//')

rule_line="include :global \"${rule_file_without_extension}\";"

echo "rule_line to remove: $rule_line"
# Remove rule line if present
sed -i "/$rule_line/d" "$sieve_file"

# Remove the rule file
rm -f "${output_dir}/${rule_filename}"

echo "Rule file removed: ${output_dir}/${rule_filename}"
echo "done"


# usage example:
# ./mailmanager_delete_rule 1234567890 user@example.com
