#!/bin/bash

# Check if all required arguments are provided
if [ $# -ne 2 ]; then
    echo "Usage: $0 rule_id email"
    exit 1
fi

rule_id="$1"
email="$2"

domain=`echo $email | awk -F@ '{print $2}'`
uname=`echo $email | awk -F@ '{print $1}'`

output_dir="/etc/dovecot/sieve"
mailhomedir="/home/vmail"
maildir="${mailhomedir}/${domain}"
user_maildir="${maildir}/${uname}"

sieve_file="${user_maildir}/.dovecot.sieve"

rule_filename=`find ${output_dir} -name "${uname}-rule-*-${rule_id}.sieve" | sed 's/^\.\///'`
rule_file_without_extension=`echo $rule_filename | sed 's/\.sieve//'` 

rule_line="include :global \"${rule_file_without_extension}\";"

# Remove rule line if present
sed -i "/$rule_line/d" "$sieve_file"

[ -f "${output_dir}/${rule_filename}" ] && rm -rf "${output_dir}/${rule_filename}" || echo "Rule file not found"


# usage example:
# ./mailmanager_delete_rule 1234567890 user@example.com
